### ISSUE TITLE
关于关闭数据库链接

### ISSUE THREAD

**Issue by skyoct** [ifwenvlook/blog#5]
我在使用flask sqlalchemy出现以下错误：sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back 根据网上搜索到的应该是为关闭数据库链接，请问您的程序是如何在操作完数据库后关闭数据库链接

**Comment by ifwenvlook** [comment]
我的程序没有处理数据库连接关闭的操作，实在不知道你的报错怎么处理。
可参考一下https://stackoverflow.com/questions/26190991/sqlalchemytornado-cant-reconnect-until-invalid-transaction-is-rolled-back
